### ISSUE TITLE
Home Page copy should include computers and tablets

### ISSUE THREAD

**Issue by rachelle-eplow** [TroyManary/EasyPlow#10]
Website indicates "a few taps on your phone" should be something like "a few simple steps" to keep the language plain a device agnostic.

<img width="368" alt="language" src="https://cloud.githubusercontent.com/assets/13750782/9280152/6bcb3972-428a-11e5-932c-bc04e6f6c51c.PNG">

**Comment by TroyManary** [comment]
Assigning to Gustave to approve and/or update the text.

**Comment by TroyManary** [comment]
Melissa, please change the text to this (from Robert):
A few clicks on your phone, tablet or computer, and your driveway will be cleared by a local snow removal expert.

**Comment by melissa-edimensionz** [comment]
Done this also, but it can only be viewed on staging for now:
http://eplow.staging0.com/en/

I also applied the txt change to production, but since the homepage redirects to /operators, it can't be viewed right now, but its up on staging for viewing :-)

**Comment by rachelle-eplow** [comment]
verified on eplow.staging0.com
