### ISSUE TITLE
Operators Home Page French: Change twitter to go_pelle

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#102]
On gopelle.com, the twitter link on Opertors home page is to the English twitter.
Change it to: twitter.com/go_pelle

![image](https://cloud.githubusercontent.com/assets/10308999/10341242/efc8cab0-6ce1-11e5-9e8f-419969286258.png)

**Comment by melissa-edimensionz** [comment]
updated

**Comment by TroyManary** [comment]
Verified on gopelle.com.
