### ISSUE TITLE
French Translation: Operator Authorization Required

### ISSUE THREAD

**Issue by melissa-edimensionz** [TroyManary/EasyPlow#103]
Need authorize error prompt translated on Operator Registration
http://eplow.staging0.com/fr/enregistrement-des-operateurs

EN
You must be authorized
FR
Vous devez être autorisé à représenter l’entreprise.

**Comment by TroyManary** [comment]
This is low priority compared to everything else that is needed for 1-Nov.

**Comment by melissa-edimensionz** [comment]
Please close this ticket, its duplicated in #101

**Comment by TroyManary** [comment]
Closed as dup of #101
