### ISSUE TITLE
French Translation: Help Page

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#104]
On the French Help Page, provide french for the following:
http://eplow.staging0.com/fr/aide

EN: the usual questions
FR: les questions habituelles

EN: get started
FR: commencez

**Comment by melissa-edimensionz** [comment]
updated on staging & production. Force fit on production.

**Comment by TroyManary** [comment]
Verified on Staging and Closed.
Not needed on production since French is not active.
