### ISSUE TITLE
French Translation: Typo on Operator Registration page

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#105]
http://eplow.staging0.com/fr/inscription-deneigeurss

The 4th word in last line needs to be fixed.  Here's the correct text from Luci:
Jetez un coup d’œil à nos secteurs de service ou soyez le premier à en desservir un nouveau.

![image](https://cloud.githubusercontent.com/assets/10308999/10488556/33cd7d0c-7267-11e5-9c53-dc86395faa6e.png)

**Comment by melissa-edimensionz** [comment]
changed staging & live

**Comment by TroyManary** [comment]
Verified on Staging and Closed.
Note: doesn't matter on live site since French is not active.
