### ISSUE TITLE
French Translation: Privacy Policy

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#109]
http://eplow.staging0.com/fr/politique-de-confidentialite
Currently the title is in French but text is English

**Comment by gustave-eplow** [comment]
​
 2015 Aug 31, PRHM_DM-_1561636-v3-E-Plow_Privacy...
<https://drive.google.com/file/d/0B-5c2BZcSghvLVZiQ20zNUlaZXFuNGR5U0lpbDlYMnYzUzFr/view?usp=drive_web>
​​
 GoPelle_Contrat de service_Version finale_SF.docx
<https://drive.google.com/file/d/0B-5c2BZcSghvZmdEbkkzeWtHVkE/view?usp=drive_web>
​

Gustave Roy
easyplow.com
gustave@easyplow.com

**Comment by TroyManary** [comment]
Thanks Gustave.
The link works, but where is this in our folders - I still can't find it 
through file explorer.
Troy

**Comment by gustave-eplow** [comment]
admin/legal/agreement/french

Gustave Roy
easyplow.com
gustave@easyplow.com

**Comment by TroyManary** [comment]
Updated Privacy Policy (French) to match the document provided by Gustave.
Noticed a couple of bullet numbering issues in the English Privacy Policy so fixed those too.

**Comment by TroyManary** [comment]
Hi Troy,
Looks great. Only one small correction to make – add the letter L and period as follows
électroniques, L.C. 2000, (LPRPDE).
Thank you.
Luci

**Comment by TroyManary** [comment]
Fixed: électroniques, L.C. 2000, (LPRPDE)
