### ISSUE TITLE
Insurance Page: Include contact info for EasyPlow Insurance company to provide assistance

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#114]
When an operator gets to the insurance page, they may need help understanding why and what needs to be done.  EasyPlow's insurance company has agreed to provide assistance.

We need to add their info to the insurance page.
http://eplow.staging0.com/en/insurance-certificate
http://eplow.staging0.com/fr/renseignements-d-assurance

**Comment by TroyManary** [comment]
Gustave, Please provide the name and contact info.  I can't find it in my emails or docs.
Thanks
Troy

**Comment by TroyManary** [comment]
From Gustave:
Our insurance specialist Rhodes & Williams Limited will be happy to answer any questions you may have about minimum coverage requirements
Karen McGregor
613-226-6630 ext 243 or toll free 1-888-391-8379 ext 243

**Comment by TroyManary** [comment]
@luci-easyplow We will insert the above text from Gustave at the end of the Insurance Form.  Please provide the french translation for the text from Gustave.

**Comment by luci-easyplow** [comment]
Notre spécialiste en assurance Rhodes & Williams Limited se fera un plaisir de répondre à vos questions sur les exigences de couverture minimale.
Karen McGregor
613-226-6630, poste 243, ou sans frais : 1-888-391-8379, poste 243

**Comment by TroyManary** [comment]
@melissa-edimensionz: please  update English and French Insurance Pages.

**Comment by melissa-edimensionz** [comment]
Done, 
Looks like French insurance is old copy

**Comment by TroyManary** [comment]
Verified the contact info is correct on Staging (both French and English)
Closing.

**Comment by TroyManary** [comment]
Melissa is correct that the french copy is out of date.
Submit a new issue for that.
