### ISSUE TITLE
Default Home Page: Slogan Banner Update

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#115]
Currently the default home page has a slogan banner that says:
    We make your life easy when it snows

Change this to
     let it snow!

**Comment by melissa-edimensionz** [comment]
updated on staging + production

**Comment by TroyManary** [comment]
Sorry Melissa, I forgot about the French Page.
Banner should be: vive la neige!

**Comment by TroyManary** [comment]
Verified English is good.

**Comment by TroyManary** [comment]
Verified on Staging.
