### ISSUE TITLE
Default Home Page: Update the Operator Image

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#116]
Currently the image in the Operator section is a placeholder blue box.
Replace it with the attached diagram:
    \Google Drive\EASYPLOW SHARED\04 UI Development\Images\map.jpg
![map](https://cloud.githubusercontent.com/assets/10308999/10615321/2522aadc-772d-11e5-9c64-80f62b41d338.jpg)

**Comment by TroyManary** [comment]
Contact Brendan if you need him to make a smaller version.

**Comment by melissa-edimensionz** [comment]
Applied to staging and production

**Comment by TroyManary** [comment]
Verified on staging (En & Fr) and Closed
