### ISSUE TITLE
Add Driver Error

### ISSUE THREAD

**Issue by melissa-edimensionz** [TroyManary/EasyPlow#118]
@AlexEdimensionz 

Can't add driver on provider account. On save, get error

Error
You are not authorised to view this resource.

**Comment by AlexEdimensionz** [comment]
This is working now. It only applied to a single account so far i can tell me2@e-dimensionz.com
There was a missing provider record for that account

**Comment by AlexEdimensionz** [comment]
Long fixed

**Comment by TroyManary** [comment]
I think this is working now.
Melissa, since you raised this one, please verify you are good with the fix.

**Comment by melissa-edimensionz** [comment]
Yup - all good. Was just my account, it was older test account
