### ISSUE TITLE
Operator Account Menu: Remove 'Add Driver' Option

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#120]
The Operator Account Menu is shown below.
Remove the 'Add Driver' option - this is not necessary since it is done through 'Manage Drivers'.
Also, Move 'Manage Drivers' up the list so it is above 'dashboard'.

![image](https://cloud.githubusercontent.com/assets/10308999/10716432/5813fc58-7b0f-11e5-9699-de0abf1cf199.png)

**Comment by TroyManary** [comment]
In Joomla Menu Manager:
--------------------------------------
   Provider EN:
      Unpublished 'Add Driver'.
      Moved 'Manage Driver' up the list.
      Also changed 'Service Preferences' to 'Edit Service Preferences' for consistency.

**Comment by TroyManary** [comment]
In Joomla Menu Manager: Provider FR:
-----------------------------------------------------
Unpublished 'Nouveau Pilote'
Moved 'Manage Conducteurs' up the list.
Also changed 'Préférences de service' to 'Modifier Préférences de service' for consistency.

**Comment by TroyManary** [comment]
Melissa, please verify I did this mod correct.
Thanks
Troy

**Comment by TroyManary** [comment]
Arrggh!  I already found a mistake.
By unpublishing 'Add Driver' I didn't just remove it from the menu, I unpublished the whole page.

How do I remove from the menu but keep the page?

**Comment by melissa-edimensionz** [comment]
Can't remove Add driver, its a page specific to accounts under the main account holder. Will need to unpublish Manage and Add Drivers, or hide Add Driver on Manage Drivers

**Comment by TroyManary** [comment]
OK everything else listed above has been fixed.  Leave 'Add Driver' in the menu as it is.
Verified on Staging and Closed.
