### ISSUE TITLE
Edit Service Area Driver Formatting Needs to be Fixed

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#121]
Edit Service Area for Operator is formatted properly, but the Edit Service Area for Driver has some strange formatting issues (see below).
1. Radius edit field is not aligned
2. Instructions appear below the menu (when screen is stretch it pops up to where it should be, but the Operator works much better)
3. Save button is not aligned
4. 'Select a Region' in top left should be 'select a region' in blue.

Make the Driver the same as Operator.

This is Operator (from Account Menu, Edit Service Area):
![image](https://cloud.githubusercontent.com/assets/10308999/10716685/0707fc12-7b17-11e5-9393-9a10650b7f3d.png)

This is Driver (from Manage Drivers, Driver Name --> Edit Service Area):
![image](https://cloud.githubusercontent.com/assets/10308999/10716687/19183e3a-7b17-11e5-94cf-8f95a0b8f1c2.png)

**Comment by melissa-edimensionz** [comment]
Try clearing browser cache, this was fixed the other day

**Comment by TroyManary** [comment]
Verified on Staging and Closed
