### ISSUE TITLE
Manage Driver display needs to be formatted/stylized

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#127]
The Manage Drivers display is functional but needs to be formatted/stylized.

It looks like this currently:
![image](https://cloud.githubusercontent.com/assets/10308999/10717478/5ef4d9aa-7b2f-11e5-9790-9a77432e844e.png)

Here is Brendan's Design:
\Google Drive\EASYPLOW SHARED\04 UI Development\Web Design V1 - Mockups\Change Requests\Multi Driver\manage_drivers_v1.jpg
![image](https://cloud.githubusercontent.com/assets/10308999/10717482/8e96088c-7b2f-11e5-88c7-73d2989a1994.png)

**Comment by melissa-edimensionz** [comment]
done

**Comment by melissa-edimensionz** [comment]
Oh - also check French version when testing - there are translations needed

**Comment by TroyManary** [comment]
@melissa-edimensionz 
I have requested translations from Luci and will add them to this issue as soon as I get them.

Do you need garbage can icons for delete?  I see them as 'X's.  Can you get the icon from the psd file?
Troy

**Comment by melissa-edimensionz** [comment]
Oops, forgot to add the code to DB on staging. Its there now. 
Just noticed the map after adding a driver is unique and styles broken. will also fix.

**Comment by melissa-edimensionz** [comment]
Fixed the map screen after Add a Driver

**Comment by TroyManary** [comment]
Hi Melissa, it looks great now!

**Comment by TroyManary** [comment]
Here are the French translations from Luci:

Manage Drivers display
--------------------------------
![image](https://cloud.githubusercontent.com/assets/10308999/10728145/d0106c54-7bb5-11e5-8235-1bbbaef08a66.png)

Edit Your Service Area display
----------------------------------------
select region = choisir votre région

**Comment by melissa-edimensionz** [comment]
Done translations, but because of the limited space - the French views will need to be adjusted to fit nicely

**Comment by TroyManary** [comment]
Sorry Melissa, we need to change some of the translations.
manage drivers
--------------------
   was: gérer les chauffeurs
   change to: gérer les opérateurs
Note: this appears in the Account menu and the title of the manage driver page

add a driver:
---------------
   was: ajouter un chauffeur
   change to: ajouter un opérateur
Note: this appears in the Account menu, the manage driver page, and the add drive page

done:
-------
   was: fait
   change to: terminé

**Comment by melissa-edimensionz** [comment]
done

**Comment by TroyManary** [comment]
Verified on staging and Closed.
manage driver = gérer les opérateurs (menu and page title)
your account = votre compte
edit service area = modifier le secteur de service
add a driver = ajouter un opérateur (menu, page title, and manage drivers button)
done =  terminé
