### ISSUE TITLE
French Translation: Operator Dashboard

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#129]
The title on this page is still in English:
http://eplow.staging0.com/fr/provider-dashboard

**Comment by TroyManary** [comment]
From Luci:
operator dashboard = tableau de bord du déneigeur

**Comment by luci-easyplow** [comment]
Concern: this page turns up as accès client on my screen
a) if we want French for "provider-dashboard", translation should read "tableau de bord du déneigeur"
b) pls note that whenever using accès client, the singular is not correct : keep plural form as follows "accès clients"

**Comment by melissa-edimensionz** [comment]
@luci-easyplow - french disabled on live on many pages, can't view. But changed the French change for operator dashboard applied 

@TroyManary - translated on production + staging

**Comment by TroyManary** [comment]
Verified on staging and closed.
