### ISSUE TITLE
French Translation: Customer Registration and Accounts

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#130]
Going through the customer registration process, discovered several untranslated items:
customer registration
welcome to easyplow
log in
remember this login?
customer dashbooard

![image](https://cloud.githubusercontent.com/assets/10308999/10733171/f7fb9cca-7bd3-11e5-85f5-cb639d8c622e.png)
![image](https://cloud.githubusercontent.com/assets/10308999/10733209/209f03c4-7bd4-11e5-8305-4773c40d4a3f.png)
![image](https://cloud.githubusercontent.com/assets/10308999/10733234/36f19448-7bd4-11e5-8f3e-51218f8665f6.png)

**Comment by TroyManary** [comment]
From Luci:
customer registration  = compte clients
welcome to easyplow = bienvenue à gopelle
log in =                           ouvrir une session
remember this login? = mémoriser mes données?
customer dashboard = tableau de bord du client

**Comment by luci-easyplow** [comment]
Please note....

mémoriser mes données : do not add a question mark to the French


thanks
Luci

**Comment by TroyManary** [comment]
OK I removed the '?' in the list above.

**Comment by melissa-edimensionz** [comment]
Done. 

Note: Login translation exists in Language Overrides - won't be live until staging -> live
** but can see on staging

**Comment by TroyManary** [comment]
Verified on Staging:
customer registration = compte clients
remember this login? = mémoriser mes données
customer dashboard = tableau de bord du client

But the Welcome page still needs french translation for 'welcome to easplow' and login.
![image](https://cloud.githubusercontent.com/assets/10308999/10749470/058ed5ec-7c41-11e5-832b-f584ea730974.png)

**Comment by melissa-edimensionz** [comment]
done on staging + production

**Comment by TroyManary** [comment]
Verified on Staging and Closed.
