### ISSUE TITLE
French Translation: Edit Service Area Page

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#131]
There are few items on this page that need translation.
Here is the translation for:
*select_region = choisir votre région

We need translations for these:
*go
*Draw a new region...

![image](https://cloud.githubusercontent.com/assets/10308999/10762473/9428e36e-7c9c-11e5-973e-0288a8a717c0.png)
![image](https://cloud.githubusercontent.com/assets/10308999/10762648/4a25fa58-7c9d-11e5-9cd4-59cedcd4e7a4.png)

**Comment by TroyManary** [comment]
Luci, I also noticed 'dashboard' is used in the top menu bar.
Is that correct?

**Comment by luci-easyplow** [comment]
Troy,

No. Translation is needed as follows

EN
dashboard
FR
tableau de bord

Luci

**Comment by luci-easyplow** [comment]
Troy,

translation needed is

EN
select region
FR
choisir votre zone

EN
go
FR
aller

EN
draw a new region
FR
tracer une nouvelle zone

IF Gustave is ok with go/aller, we'll have to change the French copy next
to it to match
appuyez ensuite sur la touche «aller»
Initially, I thought it might be fun to keep go (as in gopelle of course),
but it might not be so purposeful here.
Gustave, thoughts?


BTW - what do remettez and vider la carte stand for? Does not sound like
the right translation...

Thanks
Luci

**Comment by TroyManary** [comment]
Gustave:
When an operator is creating a service area, they enter the postal code and radius and then clikc 'Go' to draw it on the map.
In French, do you prefer 'Go' or 'Aller'?

**Comment by TroyManary** [comment]
For reference, here is the english display.
@luci-easyplow 
* reset = remettez
* clear map = vider la carte
Are these correct?

![image](https://cloud.githubusercontent.com/assets/10308999/10764153/32389652-7ca3-11e5-8481-258d41155398.png)

**Comment by luci-easyplow** [comment]
Troy,

please use the following translation

EN
reset
FR
réinitialiser

EN
clear map
FR
effacer la carte

thanks
Luci

**Comment by TroyManary** [comment]
Gustave request 'aller' instead of 'go'

**Comment by TroyManary** [comment]
@melissa-edimensionz here is the definitive list for the Edit Service Areas translations:
* reset = réinitialiser
* clear map = effacer la carte
* go = aller (both the button and the text description on right)
* select region = choisir votre zone
* Draw a New Region... = tracer une nouvelle zone...

**Comment by melissa-edimensionz** [comment]
Applied on staging, all except

> Draw a New Region... = tracer une nouvelle zone...

Its set in database. Created a new ticket:  #138

**Comment by TroyManary** [comment]
Verified on staging and closed.
![image](https://cloud.githubusercontent.com/assets/10308999/10802175/a1a1439c-7d91-11e5-9f84-d41fac8ac8d1.png)

**Comment by TroyManary** [comment]
Oops missed 1 thing.
In the instructions on right,
Change "GO" to "aller"

**Comment by luci-easyplow** [comment]
please don't forget to replace "GO" with "aller" in the script

**Comment by luci-easyplow** [comment]
awesome, thanks!

**Comment by TroyManary** [comment]
Verified GO is now aller.
Closing
![image](https://cloud.githubusercontent.com/assets/10308999/10845503/cd936144-7ede-11e5-966e-41f10a136421.png)
