### ISSUE TITLE
Fix link to Facebook GoPelle

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#132]
Unfortunately, we have a numbered account in Facebook for GoPelle.
We hope to fix in the future so we can use this:
* https://www.facebook.com/go.pelle

In the meantime, we should use the current link:
* https://www.facebook.com/GoPelle-1628315150758328/

Update all links on French pages to the current facebook page.

**Comment by melissa-edimensionz** [comment]
done

**Comment by TroyManary** [comment]
Verified on Staging:
   Operators Home Page
Closed
