### ISSUE TITLE
French Translation: Add Driver form prompts are in English

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#133]
![image](https://cloud.githubusercontent.com/assets/10308999/10765784/db4b247e-7caa-11e5-9799-d8a2200a9948.png)

**Comment by TroyManary** [comment]
@luci-easyplow: Here is the list of missing translations:
*driver first name
*driver last name
*plow
*blower

**Comment by luci-easyplow** [comment]
Hi Troy,

Here are the terms requestedL

EN
driver first name
FR
prénom de l’opérateur

EN
driver last name
FR
nom de l’opérateur

EN
plow
FR
chasse-neige

EN
blower
FR
souffleuse à neige

thanks
Luci

**Comment by melissa-edimensionz** [comment]
done

**Comment by TroyManary** [comment]
Verified and Closed
