### ISSUE TITLE
French Translation: dashboard

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#134]
The text 'dashboard' appears in several place throughout the website
The French translation is: tableau de bord

Please change it everywhere in website.
Here are places I found:
* Top Menu Bar (when logged in)
* Account Menu (operators, drivers, customers)

**Comment by melissa-edimensionz** [comment]
done -> staging & production

**Comment by TroyManary** [comment]
Verified on Staging and Closed
