### ISSUE TITLE
Login with invalid username or password shows the wrong display

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#136]
Entering an invalid username or
Entering a valid username with an incorrect password produces the display below which is meaningless to a user.
Provide a message informing them that the username or password is incorrect.

![image](https://cloud.githubusercontent.com/assets/10308999/10777888/86035ca6-7cf6-11e5-8733-1f9ad7c0e766.png)

**Comment by melissa-edimensionz** [comment]
Just a perms issue on the logs folder since there have been so many commits to staging from our dev environments. Changed the folder perms and prompts with the error

**Comment by TroyManary** [comment]
Melissa, I just tried it on staging and got the same display as before.

**Comment by melissa-edimensionz** [comment]
The perms on log folder changed since there were source commits since I updated the perms on logs.  This will keep happening on staging since there is a lot of activity with multiple computers, we will add folder to ignore

**Comment by TroyManary** [comment]
Verified on Staging and Closed.
