### ISSUE TITLE
Update App Availability Date

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#139]
The banner on the website says 'free apps available November 1st'.
Nov 1 is Sunday so we aren't going to have them ready in time.
So we MUST update the website - we will lose credibility if people show up in Nov and see Nov 1st.

1) Alex: what date do you estimate they will be available to customers?  Guess long as we don't want to keep changing it.
2) Brendan: When we get the date from Alex, produce new banners (English + French (see comment below))
3) Melissa: When you get the banner from Brendan, update the Staging & Production websites.

**Comment by TroyManary** [comment]
From Luci:
Typography of dates in French format goes as follows:
le 1er novembre, but
le 2 novembre
le 3 novembre
le 4 novembre
etc.

Only the first of the month is noted as such.

**Comment by TroyManary** [comment]
Gustave asked that we don't specify a date.
Just say "free apps available soon"

So let's go with this plan:
1) Luci: French translation
2) Brendan: 2 new banners (English, French)
3) Melissa: implement on Staging & Production

**Comment by luci-easyplow** [comment]
Here is the translation

EN
free apps
available soon
FR
applis gratuites
disponibles sous peu


Question: May I ask why we use the plural? Do we suggest that there is a
limited number of apps?

Thanks
Luci

**Comment by TroyManary** [comment]
Hi Luci, We have 2 apps. 1 for Android and 1 for Apple.
Troy

**Comment by TroyManary** [comment]
Brendan provided new banners 29-Oct-15.
Saved into this folder:
   \Google Drive\EASYPLOW SHARED\04 UI Development\Images

**Comment by melissa-edimensionz** [comment]
new banner overlays up on both staging and production

**Comment by TroyManary** [comment]
Verified on Staging on all general info pages.  And in both English and French.
Closing.
