### ISSUE TITLE
Video Issues

### ISSUE THREAD

**Issue by rachelle-eplow** [TroyManary/EasyPlow#15]
The video plays with no issues in Chrome, but with Safari, Firefox, Edge, and IE11 it has issues loading or not playing at all.
<img width="181" alt="video issues" src="https://cloud.githubusercontent.com/assets/13750782/9280686/0c267758-428e-11e5-8a97-f44283a3f88b.PNG">

**Comment by melissa-edimensionz** [comment]
Video is self hosted, some browsers need a plugin or you need to approve playing the video (settings).

**Comment by TroyManary** [comment]
Rachelle, are you able to load the plugins for the other browsers?  I just tried it in IE and the video played, so I must have already had the plugin.
Please assess how easy it is to get the plugins - will this be an issue for users?

**Comment by melissa-edimensionz** [comment]
It could be a plugin or a setting in the browser restricting flash (the plugin used for video wasn't changed). 

Doing a search for the browser + "video won't play" should give the details on what's needed.  

We can look at switching with an HTML5 video player, but some browsers still have issues and a flash video player is the fallback player for HTML5 video players.

**Comment by rachelle-eplow** [comment]
We may want to look into switching to another video player.  The video is not playing on the Ipad, and is choppy in IE11.  Still to be verified with the other browsers

**Comment by rachelle-eplow** [comment]
Can we mark this as high priority as I see this as problematic to potential operators trying to get more information on EasyPlow.  If this doesn't work as it is now and we don't have time to fix it at this point we may want to label it as "not available" "coming soon" or take it down until we have the playback issue resolved. Please advise

**Comment by gustave-eplow** [comment]
agree.
thanks Rachelle.
Gustave

**Comment by TroyManary** [comment]
Increased to High Priority as requested.

**Comment by TroyManary** [comment]
Melissa, do we have other options for embedding video?  For example, can it be loaded onto YouTube and then embedded as a link?

**Comment by melissa-edimensionz** [comment]
Yup, I had silently market this as a task to be done with the tasks, the plugin used is from the old template and it was a pain to work with

**Comment by brendan-eplow** [comment]
We have new edits of the video coming tomorrow. I think it would be best to
upload to the easyplow YouTube account, and then embed from there?

**Comment by melissa-edimensionz** [comment]
Yup - that was my thoughts for making it a little easier to make sure video support is available on all devices

**Comment by rachelle-eplow** [comment]
You guys are the best!                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Virgin Mobile network.                                                                                                                                                                                                                From: MelissaSent: Wednesday, September 9, 2015 9:31 PMTo: TroyManary/EasyPlowReply To: TroyManary/EasyPlowCc: rachelle-eplowSubject: Re: [EasyPlow] Video Issues (#15)Yup - that was my thoughts for making it a little easier to make sure video support is available on all devices

—Reply to this email directly or view it on GitHub.

**Comment by brendan-eplow** [comment]
Here are the new YouTube links for the videos:

English:
https://www.youtube.com/watch?v=7bKWiPRNySU

French:
https://www.youtube.com/watch?v=05A6-VLWaN4


Brendan Henry
*CREATIVE DIRECTOR*
<http://www.minotaurcreative.com>

**Comment by melissa-edimensionz** [comment]
Updated videos to use youtube embed

**Comment by TroyManary** [comment]
Excellent! Worked on my android phone (old one did not)


Sent from my Samsung device over Bell's LTE network.

-------- Original message --------

**Comment by TroyManary** [comment]
@rachelle-eplow Can we close this as Verified or do you want to test on other devices/browsers?

**Comment by rachelle-eplow** [comment]
Verified on IE11, Edge, Blackberry Smartphone, Safari.  Verified and closing
