### ISSUE TITLE
Operator Login does not go direct to operator dashboard

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#20]
After logging in as an operator, the main EasyPlow page is displayed.
It shows that you are logged in since there is a 'dashboard' and a 'logout' button displayed.
However, it makes more sense to go direct to the operator dashboard page.

**Comment by melissa-edimensionz** [comment]
@AlexEdimensionz  : the menu link is using CF, can a rule be set in CF when logging in via 
/en/customer-login (+ french)
/en/operator-login (+ french)

it takes the member to their dashboard

**Comment by TroyManary** [comment]
Just realized this has been fixed.

**Comment by TroyManary** [comment]
Verified and Closed
