### ISSUE TITLE
Operator Account Menu Items are not correct

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#21]
The Operator Account Menu Items (as specified in UI Dev Spreadsheet) should be:
edit your profile	
edit payment information	
dashboard	
service preferences	
coupons	
log out	

However, there are alot more options displayed:
![image](https://cloud.githubusercontent.com/assets/10308999/9586035/6b799a52-4fe8-11e5-9f94-d1c21f7aacde.png)

**Comment by melissa-edimensionz** [comment]
Menu items are easily managed through the menu manager when ready. For now, left each enabled for easy access to pages for both development of individual pages & testing.

**Comment by melissa-edimensionz** [comment]
Updated operator menu based on this ticket, 
but menu items above conflict with  https://github.com/TroyManary/EasyPlow/issues/34
(applied the other day, but this ticket still assigned and open)

Any missing menu items, please confirm they should be listed and order

**Comment by TroyManary** [comment]
Sorry I missed an item in the original comment.
Here are the items and the order they should appear:

edit your profile
edit service area
edit payment information
service preferences
dashboard
coupons
log out

**Comment by TroyManary** [comment]
Changed Priority to High since we need for current release.

**Comment by melissa-edimensionz** [comment]
done

**Comment by TroyManary** [comment]
Verified and Closed
