### ISSUE TITLE
Operator Logout should go direct to the home page

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#22]
Start off logged in as Operator.
Select logout and the screen below is displayed.
Then click on 'log out' and it takes you to the operator login page.
Would it be better to go direct to the EasyPlow home page as soon as the first 'logout' is selected?

![image](https://cloud.githubusercontent.com/assets/10308999/9586231/7f20a4d2-4fe9-11e5-81f9-90705927cd0e.png)

**Comment by TroyManary** [comment]
Brendan, Please comment on how you would like it to flow.

**Comment by brendan-eplow** [comment]
Yes, I believe it would work better to just click on the logout button and have the user directed to the home page. If they pressed it by mistake, they should be able to easily log back in

**Comment by TroyManary** [comment]
Assigned to Melissa to make all 'logout' buttons go direct to the home page.

**Comment by melissa-edimensionz** [comment]
Built in script to change logout process,

**Comment by TroyManary** [comment]
I verified that 'Logout' goes direct to the home page.
