### ISSUE TITLE
Operator Registration Progress Bar is shown even though it is not specified in UI Design

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#23]
Operator Registration is a 4 step process for Single Driver company and 5 steps for multi-driver:
1) Account Info (contact info, company info, address)
2) Insurance Certificate
3) Service Area
4) Manage Drivers (optional)
5) Payment Info

The old implementation showed a status bar in increments of 20% at each step.  This bar does not appear in the new UI design, but still appears on some displays (see below) on the actual website.

Should this bar be removed?

![image](https://cloud.githubusercontent.com/assets/10308999/9586405/b29cf008-4fea-11e5-9b0b-98649e96ce6c.png)

**Comment by brendan-eplow** [comment]
The progress bar is probably not necessary. Knowing that there are more steps to the process might make users get fed up. Generally I'd say we would only need it if the process was 6 steps or more, which would be around when the user would be wondering how many more steps are in the process

**Comment by TroyManary** [comment]
Assigned to Melissa to remove the progress bar from Operator Registration pages.

**Comment by melissa-edimensionz** [comment]
removed

**Comment by TroyManary** [comment]
Verified and Closed.
