### ISSUE TITLE
Operator Registration missing mandatory fields stars

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#24]
All fields except 'your position' and 'years in operation' should be marked as mandatory.
![image](https://cloud.githubusercontent.com/assets/10308999/9588199/d9f7b322-4ff4-11e5-8c6d-2071b38944e0.png)

**Comment by melissa-edimensionz** [comment]
Applied to fields on the left, on staging
Fields on right had "Company address" marked as required in design.

**Comment by TroyManary** [comment]
Verified and Closed.
