### ISSUE TITLE
Consumer Dashboard generates an error

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#26]
I logged into Consumer Account and pressed 'dashboard'.
The following error is displayed:
![image](https://cloud.githubusercontent.com/assets/10308999/9588465/8ae6a476-4ff6-11e5-8610-6917cc96b1fe.png)

**Comment by AlexEdimensionz** [comment]
As soon as you log in as a consumer. You hit the Dashboard page. So it works. What you were seeing at the top was a module displaying the Provider dashboard module. I added the module for consumers as well and fixed the ACL for the previous one. There was no error, just a bad link
