### ISSUE TITLE
Operator and Customer Login screens are inconsistent

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#27]
This problem is apparent when clicking back and forth between Operator Login and Customer Login.  They should be very similar.

Operator Login:
    Missing the logo and link to download apps.
    Button says 'log in' and is blue
    Text says 'remember me' in bold

Customer Login:
    Button says 'log me in' and is orange
    Text says 'remember this login?' not in bold
    Does not provide options for 'operator registration', 'customer registration'   
    
![image](https://cloud.githubusercontent.com/assets/10308999/9588777/0b226d40-4ff8-11e5-94e4-f53415ce4e5b.png)
![image](https://cloud.githubusercontent.com/assets/10308999/9588784/12cec8a4-4ff8-11e5-99b4-c42439f90567.png)

**Comment by TroyManary** [comment]
Brendan, please provide a design for the login screens that is as consistent as possible for operators and customers.  Or point us at a design to follow.

**Comment by AlexEdimensionz** [comment]
As i explained in the conference call. We dropped in a working consumer flow and fixed it up so we would have the ability to generate events for Provider reports. What you are seeing is a working implementation for that purpose

**Comment by TroyManary** [comment]
I am re-opening because we do not have a UI Design for the Login pages.
We need that to ensure we are all aligned with Brendan's design.  He has agreed to provide one.

**Comment by brendan-eplow** [comment]
Designs added to UI dev folder

**Comment by TroyManary** [comment]
Looks good.  Copied from Change Request folder into main folder.
Notified Melissa, Alex that new design is available to implement.

**Comment by rachelle-eplow** [comment]
Doesn't this get qa tested prior to implementing?                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Virgin Mobile network.                                                                                                                                                                                                                From: Troy ManarySent: Wednesday, September 2, 2015 8:45 AMTo: TroyManary/EasyPlowReply To: TroyManary/EasyPlowSubject: Re: [EasyPlow] Operator and Customer Login screens are inconsistent (#27)Looks good.  Copied from Change Request folder into main folder.
Notified Melissa, Alex that new design is available to implement.

—Reply to this email directly or view it on GitHub.

**Comment by TroyManary** [comment]
I reviewed it to make sure it was ready for implementation (same as we 
did for the other UI designs).

**Comment by rachelle-eplow** [comment]
So it gets qa tested before it's ok'd to be removed from staging then? Just want to confirm                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Virgin Mobile network.                                                                                                                                                                                                                From: Troy ManarySent: Wednesday, September 2, 2015 9:40 AMTo: TroyManary/EasyPlowReply To: TroyManary/EasyPlowCc: rachelle-eplowSubject: Re: [EasyPlow] Operator and Customer Login screens are inconsistent (#27)I reviewed it to make sure it was ready for implementation (same as we 
did for the other UI designs).


On 2015-09-02 9:31 AM, rachelle-eplow wrote:
> Doesn't this get qa tested prior to implementing? 
> Sent from my BlackBerry 10 smartphone on the Virgin Mobile network. 
> From: Troy ManarySent: Wednesday, September 2, 2015 8:45 AMTo: 
> TroyManary/EasyPlowReply To: TroyManary/EasyPlowSubject: Re: 
> [EasyPlow] Operator and Customer Login screens are inconsistent 
> (#27)Looks good. Copied from Change Request folder into main folder.
> Notified Melissa, Alex that new design is available to implement.
>
> —Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/TroyManary/EasyPlow/issues/27#issuecomment-137079666>.
>



—Reply to this email directly or view it on GitHub.
