### ISSUE TITLE
Customer login not rendering correctly_chrome browser

### ISSUE THREAD

**Issue by gustave-eplow** [TroyManary/EasyPlow#28]
http://eplow.staging0.com/en/operator-signup

![http- eplow staging0 com en operator-signup](https://cloud.githubusercontent.com/assets/13750767/9650065/91c3128a-51cb-11e5-8af9-125c4cc66672.jpg)

**Comment by TroyManary** [comment]
When viewed on wide-screen 'customer login' is displayed on one line, as expected.
As the screen narrows, the 'customer login' squishes to 2 lines, which is expected.
However, it seems to squish sooner than it needs to.

Can the element width be increased so it doesn't squish until necessary?

**Comment by melissa-edimensionz** [comment]
Fixed this. 
Need to revisit smaller screens though once consumer done

**Comment by melissa-edimensionz** [comment]
Didn;t update staging yet - reassigned to me

**Comment by melissa-edimensionz** [comment]
fix on staging for screen resolution 1366px, clear browser cache

**Comment by TroyManary** [comment]
Verified it stays on 1 line until it switches to the single 'login' when it gets narrow.
Note: the 'user head' still drops to a 2nd line just before it switches, but that is OK for now.  We will do more screen size checks later.
