### ISSUE TITLE
'home-operator' page must be moved to 'operators'

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#29]
The promo material for Operators has been published with this URL:
http://www.easyplow.com/operators

Please move it from the current URL:
http://www.easyplow.com/en/home-operator

**Comment by melissa-edimensionz** [comment]
Page is blank

**Comment by TroyManary** [comment]
Hi Melissa,  I put the 'deployed' address which is blank.  They equivalent in staging is:
http://eplow.staging0.com/en/home-operator

**Comment by melissa-edimensionz** [comment]
changed : http://eplow.staging0.com/en/operator

**Comment by TroyManary** [comment]
Hi Melissa, sorry to be picky but it needs to be 'operators' not 'operator' to match the ad.
Troy

**Comment by melissa-edimensionz** [comment]
Fixed: http://eplow.staging0.com/en/operators

**Comment by TroyManary** [comment]
Verified the page is at URL: http://eplow.staging0.com/en/operators
