### ISSUE TITLE
Help: Answer text is incorrect for some questions

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#3]
'can I get snow cleared from more than one address?': the answer to this is under question above it.
'what if i'm not satisfied': this is not the correct answer - need Gustave to provide an answer.

**Comment by melissa-edimensionz** [comment]
This is the same on Production, just need the updated text to apply to staging database:
https://www.easyplow.com/en/help

**Comment by TroyManary** [comment]
Gustave, Please provide correct text.

**Comment by gustave-eplow** [comment]
Hi troy - when I get stuff like this, do I send answers via email or do I
log into github and do it through there?

**Comment by rachelle-eplow** [comment]
You do it through github :)                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Virgin Mobile network.                                                                                                                                                                                                                From: gustave-eplowSent: Thursday, August 13, 2015 10:42 PMTo: TroyManary/EasyPlowReply To: TroyManary/EasyPlowSubject: Re: [EasyPlow] Help: Answer text is incorrect for some questions (#3)Hi troy - when I get stuff like this, do I send answers via email or do I
log into github and do it through there?

On Thu, Aug 13, 2015 at 8:17 AM, Troy Manary <notifications@github.com>
wrote:

> Gustave, Please provide correct text.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TroyManary/EasyPlow/issues/3#issuecomment-130646303>.
>


—Reply to this email directly or view it on GitHub.

**Comment by TroyManary** [comment]
It's best if you can do it in github so it keeps all the info together. I need to give you a guide to make it easier.  I will send it to you tomorrow.Troy


Sent from my Samsung device over Bell's LTE network.

-------- Original message --------

**Comment by TroyManary** [comment]
Help Q&A is here: https://drive.google.com/file/d/0B-5c2BZcSghvTVNUc3hDNnlOTnd3MUZoTnRMZ3Y4dzNCc2hF/view?usp=sharing

**Comment by TroyManary** [comment]
The missing text for the question raised in this issue is:
If your snow clearing service is not acceptable, you can file a claim with the independent operator. Payment will be suspended until the problem is resolved.

**Comment by melissa-edimensionz** [comment]
Updated

**Comment by TroyManary** [comment]
Verified Help text is good.
