### ISSUE TITLE
Marketing landing page

### ISSUE THREAD

**Issue by AlexEdimensionz** [TroyManary/EasyPlow#32]
A new marketting document has been created: operatorpitchdocument_01.pdf (see Google Drive Branding & Marketting Folder).

This document needs to be integrated with the existing Operator Landing Page:
http://eplow.staging0.com/en/operators

**Comment by TroyManary** [comment]
Here are the options I came up with:
1) Replace the operator home page with a new page based on the Pitch Document:
2) Add a link on the 2 Home Pages to Download the pdf
3) Combination of 1 & 2: Tweak the operator home page with some of the Pitch Document and provide a link to download the full pdf for more details.

In terms of effort, #1 is alot, #2 is a little, and #3 is in between.

In terms of marketting, what is the best approach?  Do you have other options?

**Comment by melissa-edimensionz** [comment]
Updated existing page, updated image and linked to PDF (read more button)
Not sure if this will work:
http://eplow.staging0.com/en/operators

**Comment by gustave-eplow** [comment]
Brendan, please send our logo to Melissa.
We now have the final version!
Gustave

**Comment by melissa-edimensionz** [comment]
Updated the logos and icons wirth the new logo. You may need to clear 
browser cache to view the change, I didn't change the filename. 

On Sun, Sep 6, 2015 at 6:24 PM, gustave-eplow <notifications@github.com> 
wrote:

> Brendan, please send our logo to Melissa.
> We now have the final version!
> Gustave
>
> On Sat, Sep 5, 2015 at 10:45 PM Melissa <notifications@github.com> wrote:
>
> > Updated existing page, updated image and linked to PDF (read more button)
> > Not sure if this will work:
> > http://eplow.staging0.com/en/operators
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/TroyManary/EasyPlow/issues/32#issuecomment-138033165
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/TroyManary/EasyPlow/issues/32#issuecomment-138132693>.
>



-- 


e-dimensionz Inc

www.e-dimension.com

Google+: google.com/+E-dimensionz

Facebook: facebook.com/edimensionz

LinkedIN: ca.linkedin.com/in/edimensionz

Twitter: twitter.com/edimensionz

Blog: e-dimensionz.com/blog/

**Comment by TroyManary** [comment]
We have settled on option 3 for now.
The operators home page is a scaled down version of the brochure.  If they want to see the entire brochure, click 'Read More'.
Verified and Closed.
