### ISSUE TITLE
Main Home Page is missing the Interactive Map

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#33]
There are 2 home pages.  The Main home page is the default: http://eplow.staging0.com/en/
The Operator's Home page is at: http://eplow.staging0.com/en/operators

The Main Home Page is missing the Interactive Map that appears on the Operator's Home Page.

**Comment by AlexEdimensionz** [comment]
Hmm. What exactly is the interactive map supposed to be?

**Comment by gustave-eplow** [comment]
The interactive map is a visual which to allows operators to slide the 
scale to the right and see additional on-demand service calls appear in 
their regular route.
Low priority - let's use existing visual from our ad instead.
Brendan can resize the image & remove the copy for it to fit into the 
space; recycle the copy on the side of the image.
Gustave

> AlexEdimensionz <mailto:notifications@github.com>
> September 5, 2015 at 9:02 AM
>
> Hmm. What exactly is the interactive map supposed to be?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/TroyManary/EasyPlow/issues/33#issuecomment-137952429>.
>
> Troy Manary <mailto:notifications@github.com>
> September 4, 2015 at 8:04 PM
>
> There are 2 home pages. The Main home page is the default: 
> http://eplow.staging0.com/en/
> The Operator's Home page is at: http://eplow.staging0.com/en/operators
>
> The Main Home Page is missing the Interactive Map that appears on the 
> Operator's Home Page.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/TroyManary/EasyPlow/issues/33>.
>

-- 
Sent with Postbox <http://www.getpostbox.com>

**Comment by AlexEdimensionz** [comment]
There is no specification for it. Not sure how we would know their existing route for a non-logged in user. Otherwise, did you just mean an animated image that gives an example? If So, we don't have one provided

**Comment by TroyManary** [comment]
Putting On Hold for now.
For the current release, the Default Home Page re-directs to the Operators Home Page.  On the Operators Home Page we have decided to display the promo map instead.  So this is not an issue.

Need to re-visit the map capability for the next release.

**Comment by melissa-edimensionz** [comment]
Please prepare the specs / functionality rules as early as possible to ensure its included with the official launch  (to allow for development time)

**Comment by TroyManary** [comment]
We will stick with the promo map that is currently on the Operators Home Page.
Please copy it to the Default Home Page.
Note: I hope that it will be big enough to read.  If not, we will have to figure out what else can be done.

**Comment by gustave-eplow** [comment]
Troy,

We are using this image without the copy & adding the same text to the 
right of the image on the Operator Home page.
Just got off the phone with Melissa, we are completely aligned, I'd like 
the home page to be done the same way.
Gustave


Troy Manary wrote:

**Comment by melissa-edimensionz** [comment]
Not sure what is needed here.

**Comment by TroyManary** [comment]
We have a static cartoon now.
No intent to change this in the near future so closing out this Issue,
