### ISSUE TITLE
Update Navigation for Sept 15th

### ISSUE THREAD

**Issue by melissa-edimensionz** [TroyManary/EasyPlow#34]
re: UI Organization.ppt (google drive)
https://drive.google.com/a/e-dimensionz.com/file/d/0B2OWnLXln7nvS2c4Y3l6bnZMc3M/view

**Comment by melissa-edimensionz** [comment]
@AlexEdimensionz , @TroyManary @gustave-eplow 
Pages / Elements hidden (i.e. reports, coupons, consumer login) are only hidden to users logged in. Administrators can still view the pages / elements if you log into the website with the admin user/password via Operator Login. This will allow us to still access the pages for testing & continued work

Let me know if any links were missed

**Comment by TroyManary** [comment]
Here are the menu items and the order they should appear.
NOTE: the coupons item should be disabled for 15-Sept launch - everything else is good.

edit your profile
edit service area
edit payment information
service preferences
dashboard
coupons
log out

**Comment by TroyManary** [comment]
I will hold onto this one for now.  When Issue #21 is fixed, then this can be verified too.

**Comment by TroyManary** [comment]
Issue #21 is fixed and verified.

**Comment by TroyManary** [comment]
Closing along with Issue #21.
