### ISSUE TITLE
Update Service Areas 

### ISSUE THREAD

**Issue by melissa-edimensionz** [TroyManary/EasyPlow#35]
http://eplow.staging0.com/en/service-areas

**Comment by AlexEdimensionz** [comment]
@TroyManary @gustave-eplow What are we doing with this page? The functionality has changed since day 1 - Originally you guys wanted to draw city polygons using the administrative back-end. There is no spec/design for it for the new iteration of the site. I only imported the view and added a menu item for completeness during the planning phase. Should be just disable it?

**Comment by gustave-eplow** [comment]
I'm fine with disabling it.  Let's revisit when we've got registered 
guy's (and girls lol:-)
The idea is to show which areas have been selected by operators / 
coverage - not all that useful if no operators registered.


> AlexEdimensionz <mailto:notifications@github.com>
> September 5, 2015 at 9:48 AM
>
> @TroyManary <https://github.com/TroyManary> @gustave-eplow 
> <https://github.com/gustave-eplow> What are we doing with this page? 
> The functionality has changed since day 1 - Originally you guys wanted 
> to draw city polygons using the administrative back-end. There is no 
> spec/design for it for the new iteration of the site. I only imported 
> the view and added a menu item for completeness during the planning 
> phase. Should be just disable it?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/TroyManary/EasyPlow/issues/35#issuecomment-137957594>.
>
> Melissa <mailto:notifications@github.com>
> September 4, 2015 at 10:38 PM
>
> http://eplow.staging0.com/en/service-areas
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/TroyManary/EasyPlow/issues/35>.
>

-- 
Sent with Postbox <http://www.getpostbox.com>

**Comment by AlexEdimensionz** [comment]
That's fine.. It's doable..

But this is a shift from the original Idea. I propose that an interval 
process reduces the drawn regions that are in the database to city-based 
polygons, then I can add polygon-combining math to end up with per-city 
snapshots of drawn areas. That's for after the demo though

Alex

e-dimensionz Inc.
Tel: 226.444.8466
Mob: 226.338.8980
http://e-dimensionz.com

**Comment by gustave-eplow** [comment]
perfect. thanks Alex.
G

> AlexEdimensionz <mailto:notifications@github.com>
> September 5, 2015 at 10:03 AM
> That's fine.. It's doable..
>
> But this is a shift from the original Idea. I propose that an interval
> process reduces the drawn regions that are in the database to city-based
> polygons, then I can add polygon-combining math to end up with per-city
> snapshots of drawn areas. That's for after the demo though
>
> Alex
>
> e-dimensionz Inc.
> Tel: 226.444.8466
> Mob: 226.338.8980
> http://e-dimensionz.com
> On 2015-09-05 04:57 PM, gustave-eplow wrote:
> > I'm fine with disabling it. Let's revisit when we've got registered
> > guy's (and girls lol:-)
> > The idea is to show which areas have been selected by operators /
> > coverage - not all that useful if no operators registered.
> >
> >
> > > AlexEdimensionz <mailto:notifications@github.com>
> > > September 5, 2015 at 9:48 AM
> > >
> > > @TroyManary <https://github.com/TroyManary> @gustave-eplow
> > > <https://github.com/gustave-eplow> What are we doing with this page?
> > > The functionality has changed since day 1 - Originally you guys wanted
> > > to draw city polygons using the administrative back-end. There is no
> > > spec/design for it for the new iteration of the site. I only imported
> > > the view and added a menu item for completeness during the planning
> > > phase. Should be just disable it?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > >
> > 
> <https://github.com/TroyManary/EasyPlow/issues/35#issuecomment-137957594>.
> > >
> > > Melissa <mailto:notifications@github.com>
> > > September 4, 2015 at 10:38 PM
> > >
> > > http://eplow.staging0.com/en/service-areas
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/TroyManary/EasyPlow/issues/35>.
> > >
> >
> > --
> > Sent with Postbox <http://www.getpostbox.com>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/TroyManary/EasyPlow/issues/35#issuecomment-137957960>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/TroyManary/EasyPlow/issues/35#issuecomment-137958181>.
>
> Melissa <mailto:notifications@github.com>
> September 4, 2015 at 10:38 PM
>
> http://eplow.staging0.com/en/service-areas
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/TroyManary/EasyPlow/issues/35>.
>

-- 
Sent with Postbox <http://www.getpostbox.com>

**Comment by melissa-edimensionz** [comment]
Made it a coming soon page for now: 
http://eplow.staging0.com/en/service-areas

**Comment by gustave-eplow** [comment]
Good morning,
The service area map would not save this AM.  Google Chrome browser.
see attached.
Gustave

> Melissa <mailto:notifications@github.com>
> September 5, 2015 at 10:43 PM
>
> Made it a coming soon page for now:
> http://eplow.staging0.com/en/service-areas
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/TroyManary/EasyPlow/issues/35#issuecomment-138033101>.
>
> Melissa <mailto:notifications@github.com>
> September 4, 2015 at 10:38 PM
>
> http://eplow.staging0.com/en/service-areas
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/TroyManary/EasyPlow/issues/35>.
>

-- 
Sent with Postbox <http://www.getpostbox.com>

**Comment by melissa-edimensionz** [comment]
Fixed

**Comment by TroyManary** [comment]
Reducing priority to Medium since this is not required for current release.

**Comment by AlexEdimensionz** [comment]
What's missing with this? It's fixed. Unless i'm missing something

**Comment by TroyManary** [comment]
I don't think we have settled on what the service area page is supposed to look like.
I will review what we have determine with Gustave if it is OK or if a change request is necessary.
Closing this Issue
