### ISSUE TITLE
MacBook Air - Footer Fix

### ISSUE THREAD

**Issue by melissa-edimensionz** [TroyManary/EasyPlow#36]
On MacBook Air - 10px black bar above the footer

**Comment by melissa-edimensionz** [comment]
Should be okay now, but may need to clear browser cache to view the footer fix

**Comment by TroyManary** [comment]
Rachelle, do you have a macbook air that you can verify this on?

**Comment by rachelle-eplow** [comment]
Nope but I can check it on the iPad                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Virgin Mobile network.                                                                                                                                                                                                                From: Troy ManarySent: Tuesday, September 8, 2015 3:10 PMTo: TroyManary/EasyPlowReply To: TroyManary/EasyPlowCc: rachelle-eplowSubject: Re: [EasyPlow] MacBook Air - Footer Fix (#36)Rachelle, do you have a macbook air that you can verify this on?

—Reply to this email directly or view it on GitHub.

**Comment by rachelle-eplow** [comment]
I have verified it is not present on the iPad.  If the problem persists we can submit a new issue
