### ISSUE TITLE
How It Works Page: small typo

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#37]
This line:
nearest available operato(or your preferred operator

Should be:
nearest available operator or your preferred operator

**Comment by TroyManary** [comment]
On same page, this line:
Save your timfor more important things and let experts take care of clearing youdriveway when the snow flies.

Should be:
Save your time for more important things and let experts take care of clearing your driveway when the snow flies.

**Comment by melissa-edimensionz** [comment]
updated

**Comment by TroyManary** [comment]
Verified and closed.
