### ISSUE TITLE
Privacy Policy Copy Update

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#38]
Please update the Privacy Policy page with the content in this doc:
  \Google Drive\EASYPLOW SHARED\01 Business Development\documents\
       2015 Aug 31, PRHM_DM-_1561636-v3-E-Plow_Privacy_Policy.docx

**Comment by melissa-edimensionz** [comment]
done

**Comment by TroyManary** [comment]
Verified and Closed
