### ISSUE TITLE
Terms and Conditions Copy Update

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#39]
Please update the Privacy Policy page with the content in this doc:
\Google Drive\EASYPLOW SHARED\01 Business Development\documents\
2015 Aug 31, PRHM_DM-_1560925-v5-E-Plow_Terms_of_Use.doc

**Comment by melissa-edimensionz** [comment]
done

**Comment by TroyManary** [comment]
Verified and Closed
