### ISSUE TITLE
Update Service Agreement

### ISSUE THREAD

**Issue by melissa-edimensionz** [TroyManary/EasyPlow#41]
Replace Service Agreement: http://easyplow.com/en/accept-agreement/

File here: https://drive.google.com/file/d/0B_j1G_SyI74tTDh0N3AwenJ2YmM/view?usp=sharing

**Comment by melissa-edimensionz** [comment]
Updated
http://www.easyplow.com/en/accept-agreement

**Comment by TroyManary** [comment]
Hi Melissa, Sorry to be so picky.  Please change the title from 'ePlow Online Service Agreement' to 'Easyplow Online Service Agreement' so it matches the legal document.

**Comment by melissa-edimensionz** [comment]
Done

**Comment by TroyManary** [comment]
Verified and Closed.
Used notepad++ (text editor) to compare web text and original doc text.
