### ISSUE TITLE
Operator pdf Brochure: Change Hyper links

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#42]
Gustave has requested the following changes to operators.pdf:

1) At the bottom of the pdf, there are 3 boxes for Marketing, Coupons, and Service.  Each box has a 'more...' link.  Please remove these links as there is nowhere to go currently.
2) At the bottom of the pdf, there is text:
         Additional information available at easyplow.com/operators
    Change this to:
         Operator Signup at www.easyplow.com/en/operator-registration
          (make this a hyper link that can be clicked)

**Comment by TroyManary** [comment]
Gustave needs 2 versions of this pdf - an online version (for the website) and an indpendent version that can be attached to email.

For the online version, only need a hyperlink to 'operator-registration'.
For the email attachment, need both hyperlinks to 'operators' and 'operator-registration'.

Maybe it is easiest just to include both links and have only 1 version?

**Comment by TroyManary** [comment]
Brendan has updated the pdf:
Google Drive\EASYPLOW SHARED\08 Branding and Marketing_\Operator Document\operatordoc_online.pdf

Replace the current doc on website that is at this location:
http://www.easyplow.com/images/media/operators.pdf

**Comment by melissa-edimensionz** [comment]
Replaced pdf

**Comment by TroyManary** [comment]
Verified and Closed
