### ISSUE TITLE
Operator needs mechanism to update insurance certificate

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#43]
Currently, the operator is required to submit their certificate during registration - which is correct behvaviour.
However, it may be necessary for them to update the certificate after they have completed the registration process.  This might happen if there is an error in their original submission, info has changed, or they registered with an invalid document.

Under the 'Your Account' Menu for Operators, provide an option to 'Update Insurance Certificate' which takes them to the same page that is used during registration.

**Comment by AlexEdimensionz** [comment]
If there is an error in their original submission, then it gets rejected 
and they get directed back to the insurance page next time they log in. 
Basically they can keep uploading insurance forms until they are marked 
as "approved" in the admin page

Alex

e-dimensionz Inc.
Tel: 226.444.8466
Mob: 226.338.8980
http://e-dimensionz.com

**Comment by TroyManary** [comment]
That makes sense.  That will cover the cases where we have a problem with their certificate.
In the cases where they want to upload a new certificate (not very likely) they can contact us and we can manually reset the database flag so they are prompted next login.

Closing as a non-issue.
