### ISSUE TITLE
Change Language Flags to Words

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#44]
Gustave, Melissa, and I discussed this previously.  It may be offensive to some people that English is represented as Canada's flag and French is France's flag.

Robert suggests that we just use words instead of flags: 'English' and 'Francais'.

**Comment by melissa-edimensionz** [comment]
Replaced flags. Used abbreviation for space / readability

**Comment by TroyManary** [comment]
Hi Melissa, please change the hover text from 'French' to 'Francais'.

**Comment by melissa-edimensionz** [comment]
Done

**Comment by TroyManary** [comment]
Verified and Closed
