### ISSUE TITLE
Page/confirmation message offset to the right

### ISSUE THREAD

**Issue by gustave-eplow** [TroyManary/EasyPlow#45]
http://www.easyplow.com/en/operator-registration?chronoform=provider_registration&event=submit

message box & app visual offset on confirmation (Step 1) web page.
Message box/copy is kind of large too...
Safari/macbook pro
![http- www easyplow com en operator-registration chronoform provider_registration event submit](https://cloud.githubusercontent.com/assets/13750767/9750266/609f4b32-5663-11e5-9cd9-fc51f2747154.png)

**Comment by melissa-edimensionz** [comment]
fixed

**Comment by TroyManary** [comment]
Verified on easyplow.com.
