### ISSUE TITLE
Download app visual is offset blocking copy

### ISSUE THREAD

**Issue by gustave-eplow** [TroyManary/EasyPlow#46]
http://www.easyplow.com/en/insurance-certificate
Chrome/macbook pro

Step 3 upload insurance certificate page
<img width="1302" alt="http- www easyplow com en insurance-certificate" src="https://cloud.githubusercontent.com/assets/13750767/9751444/009a75d0-5673-11e5-94f7-695595526734.png">

**Comment by melissa-edimensionz** [comment]
Fixed so it doesn't cover text

**Comment by TroyManary** [comment]
Verified and Closed
