### ISSUE TITLE
Operator Sign Up and Read More Selection Areas

### ISSUE THREAD

**Issue by rachelle-eplow** [TroyManary/EasyPlow#47]
Selection Areas need to be expanded to designated area rather than just the title

See Image Below
![selection areas](https://cloud.githubusercontent.com/assets/13750782/9752528/9d8496bc-567f-11e5-9fcc-9695388e4dfe.PNG)

**Comment by TroyManary** [comment]
Hi Rachelle, I don't understand the issue here.  Can you add more description?

**Comment by TroyManary** [comment]
Sorry I just figured it out.
When I click with the mouse, it only works over the text.  It does nothing over the arrows or the blank space after the text.

**Comment by melissa-edimensionz** [comment]
Fixed

**Comment by rachelle-eplow** [comment]
Verified Fix
