### ISSUE TITLE
Operator Login Information not Remembered

### ISSUE THREAD

**Issue by rachelle-eplow** [TroyManary/EasyPlow#48]
Login information not remembered after "remember me" is selected.  All browsers

**Comment by melissa-edimensionz** [comment]
Can't recreate issue, I have been logged into EasyPlow as an operator since yesterday. 

Most likely browser related. Either cookies are being blocked, the browser's privacy setting, or even an Anti-virus "personal info" setting is preventing the cookie from being saved.

**Comment by TroyManary** [comment]
I just tried it with Chrome in Windows 8.  It does not remember me.
I confirmed that Cookies are enabled.

Here's what I did:
0) start at easyplow.com
1) select 'operator login'
2) login as an operator and click 'remember me'
3) takes me to the operator dashboard
4) Chrome pops up a prompt to remember password - click Nope.
4) select logout from menu bar
5) select operator login
6) login screen displayed but fields are all empty.

If I do the exact same procedure, but when Chrome prompts me, I select 'Save Password' then it does remember me on the next login.  But this works regardless of whether or not I select the 'remember me' checkbox embedded in page.

**Comment by melissa-edimensionz** [comment]
You need to set Chrome to Save Passwords for what you are trying to do above. 

Remember Me:
Log in, close browser or navigate away from the site (without logging out). Return - you are still logged in. Remember me sets a cookie to keep logged in status alive

**Comment by TroyManary** [comment]
OK I misunderstood how it worked.
However, something still doesn't seem right - it remembers me whether the box is checked or not.

Here's what I did:
0) start at easyplow.com
1) select 'operator login'
2) login as an operator.
3) DO NOT click 'remember me'
4) takes me to the operator dashboard
5) Chrome pops up a prompt to remember password - click Nope.
6) close Chrome
7) open Chrome
8) goto easyplow.com
9) I get the home page and I am logged in already

The same thing happens if I select remember me at step 3.

**Comment by melissa-edimensionz** [comment]
RE 5: Chrome pops up a prompt to remember password - click Nope
-> browser setting, you need to set chrome to save passwords

RE 9: 9) I get the home page and I am logged in already

--> You have a cookie set from a previous login
- Log out of site, close tab to site. Clear cookies. Restart browser

**Comment by rachelle-eplow** [comment]
I'm not getting anything in IE either                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Virgin Mobile network.                                                                                                                                                                                                                From: MelissaSent: Wednesday, September 9, 2015 11:31 AMTo: TroyManary/EasyPlowReply To: TroyManary/EasyPlowCc: rachelle-eplowSubject: Re: [EasyPlow] Operator Login Information not Remembered (#48)RE 5: Chrome pops up a prompt to remember password - click Nope
-> browser setting, you need to set chrome to save passwords

RE 9: 9) I get the home page and I am logged in already

--> You have a cookie set from a previous login


Log out of site, close tab to site. Clear cookies. Restart browser 


—Reply to this email directly or view it on GitHub.

**Comment by melissa-edimensionz** [comment]
Same answer for IE as Chrome (all browsers).

Re Saving Password:
Need to enable browser to save password

Re: not staying logged in when leaving the page
Related to cookies being blocked, the browser's privacy setting, or even an Anti-virus "personal info" setting is preventing the cookie from being saved.  

Re Still Logged in when closing browser and not selecting "Remember Me"
Cookie set from recent previous attempt. Log Out > Close site tab >  > Clear Cookies > Restart Browser

**Comment by melissa-edimensionz** [comment]
Below sent to Troy to explain how Cookies & Remember Me works. This is global (common) behaviour on the Remember Me option on websites. Adding my email note to ticket for everyone to reference:

Remember Me stores a cookie on your computer. If you clicked Remember Me yesterday, the cookie still exists, even if you don't click Remember Me today.  The cookie is stored on your machine until it expires or is manually removed

To test how Remember Me works when not checked, you need to clear the cookie already stored on your computer from a previous login. (follow steps above in earlier ticket note)

**Comment by TroyManary** [comment]
OK! Talked to Melissa and now I get it.  Ignoring cookies and browser settings, here is what the button does.

If you login and DO NOT select 'remember me':
--> You stay logged in until:
    a)  you explicitly log out or 
    b) after an expiry timeout (not sure exactly what the timeout is).

If you login and DO select 'remember me':
--> You stay logged in until:
     a) you explicitly log out

**Comment by TroyManary** [comment]
So to test the 'remember me' button:
1) login and DO NOT select 'remember me'
2) close the browser
3) periodically reopen easyplow
4) eventually you should get logged out

Repeat
1) login and DO select 'remember me'
2) close the browser
3) wait for longer than the previous test and reopen easyplow
4) you should still be logged in

**Comment by rachelle-eplow** [comment]
Verified
