### ISSUE TITLE
Wrong Information Input

### ISSUE THREAD

**Issue by rachelle-eplow** [TroyManary/EasyPlow#49]
We were testing the Operator Sign Up for wrong information input such as wrong email address, postal code format, telephone number format, etc...and the only indication we got was near the password field.  See image below...(we are getting a little punchy..for your reading pleasure and please keep in mind this is all in fun but still a problem all the same...

![ezplow wrong input](https://cloud.githubusercontent.com/assets/13750782/9752651/d9b2f902-5680-11e5-836f-e9fd1a821d1b.JPG)

**Comment by TroyManary** [comment]
Melissa, Alex, Which fields have format checking on them?
I know password does but I am not sure that other do.
As a minimum, I think email should be checked for valid format since it will be used to send message.

**Comment by melissa-edimensionz** [comment]
Done

**Comment by TroyManary** [comment]
Rachelle, Please verify.

**Comment by rachelle-eplow** [comment]
Verified
