### ISSUE TITLE
Safari, Firefox Header

### ISSUE THREAD

**Issue by rachelle-eplow** [TroyManary/EasyPlow#5]
Header shows "world, user login" on left and menu on Right.  As opposed to the Chrome header which shows world on right and menu on left.  Safari and Firefox is also missing footer "Customer Login" "We Make your Life Easy When it Snows" and Operator Signin.
<img width="304" alt="safari-firefox header" src="https://cloud.githubusercontent.com/assets/13750782/9279707/451c9a9e-4287-11e5-8b7b-d8188c92c5f3.PNG">

**Comment by melissa-edimensionz** [comment]
Mobile views show only "login", desktop shows operator and consumer login links. There is also text changes on mobile, some sections hidden   (see designs in Google Drive) 

Re login links: can be changed, though may need to restructure mobile header for sizing / usability  (spacing on small screens is likely the reason Brendan changed Mobile to only show "login" in the designs - it stays big text and easily seen)

**Comment by TroyManary** [comment]
Rachelle, based on previous comment from Melissa, does the implementation of 'login' follow the designs laid out by Brendan?

**Comment by rachelle-eplow** [comment]
Verified it follows mobile mockup.  And is intuitive to the login being customer or operator
