### ISSUE TITLE
Edit Profile Wording Overlap

### ISSUE THREAD

**Issue by rachelle-eplow** [TroyManary/EasyPlow#51]
While editing profile if a field is not filled in correctly and text prompt is populated by the title of the page.  There is an overlap with the title
![editprofile wording overlap](https://cloud.githubusercontent.com/assets/13750782/9765486/6609e08a-56e2-11e5-9a9a-e7e804be56d0.png)

**Comment by melissa-edimensionz** [comment]
Fixed

**Comment by rachelle-eplow** [comment]
Fix Verified
