### ISSUE TITLE
Edit Profile email population issue

### ISSUE THREAD

**Issue by rachelle-eplow** [TroyManary/EasyPlow#52]
If a user changes the email address and doesn't confirm the email address in the confirm field- after saving a going back into the edit profile area the confirm email address field is populated with the updated email address.  That said if you save the edit profile you cannot log back into your operator account.  Is the operator supposed to get an email confirmation on the new account information or what happens in this case. This image is from the "Edit Profile" page after the email address was updated but not confirmed.  Hope this makes sense.
![emailaddress](https://cloud.githubusercontent.com/assets/13750782/9765601/12a6542c-56e3-11e5-9ff7-bc767ef6e530.png)

**Comment by TroyManary** [comment]
Hi Rachelle,  I don't understand the steps to produce this.
Here's what I tried:
1) edit my profile
2) changed my email address (did not change 'confirm email address)
3) hit save
4) I get an error message on confirm field: Please make sure that the value matches the email field value.

Do you not get this error message?

**Comment by rachelle-eplow** [comment]
I didn't last night. I will try again                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Virgin Mobile network.                                                                                                                                                                                                                From: Troy ManarySent: Wednesday, September 9, 2015 11:26 AMTo: TroyManary/EasyPlowReply To: TroyManary/EasyPlowCc: rachelle-eplowSubject: Re: [EasyPlow] Edit Profile email population issue (#52)Hi Rachelle,  I don't understand the steps to produce this.
Here's what I tried:
1) edit my profile
2) changed my email address (did not change 'confirm email address)
3) hit save
4) I get an error message on confirm field: Please make sure that the value matches the email field value.

Do you not get this error message?

—Reply to this email directly or view it on GitHub.

**Comment by rachelle-eplow** [comment]
I cannot reproduce issue.  I will close this for now
