### ISSUE TITLE
Copy changes from PR

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#55]
Robert has reviewed and updated the copy for General Info and Operator Registration/Login/Logout/Edit Account.
The changes are captured in this doc on Google Drive:
04 UI Development\Copy\operators - Screen Shots.pptx

**Comment by TroyManary** [comment]
Set Priority to High to get site finalized before operators start showing up to register.

**Comment by AlexEdimensionz** [comment]
Just English?

**Comment by TroyManary** [comment]
Oui!

**Comment by gustave-eplow** [comment]
french on it's way; figured we'll get English perfect first.
Gustave

AlexEdimensionz wrote:

**Comment by melissa-edimensionz** [comment]
Done

**Comment by TroyManary** [comment]
Verified and Closed.
