### ISSUE TITLE
Copy changes and reformat to Operators Home Page

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#56]
Robert has reviewed and updated the copy for Operators Home Page.
He has also proposed some format changes.

The changes are captured in this doc on Google Drive:
08 Branding and Marketing_\PR POST\Operators page.docx

**Comment by melissa-edimensionz** [comment]
@gustave-eplow @TroyManary @brendan-eplow 
Created a rough draft with the text changes on Staging: http://eplow.staging0.com/en/operators

Before finalizing and updating production, let me know if anything should be changed.

Reference: link to doc: https://drive.google.com/file/d/0B-5c2BZcSghvcWNvSmhaLWozZWVHdnZZYklxMjAxN3QydDgw/view?usp=sharing

**Comment by gustave-eplow** [comment]
Thanks for the quick turnaround M.
That's essentially it;-)
Robert-> take a look at the following staging link and share final edits.
G'night
Gustave



> Melissa <mailto:notifications@github.com>
> September 10, 2015 at 11:13 PM
>
> @gustave-eplow <https://github.com/gustave-eplow> @TroyManary 
> <https://github.com/TroyManary> @brendan-eplow 
> <https://github.com/brendan-eplow>
> Created a rough draft with the text changes on Staging: 
> http://eplow.staging0.com/en/operators
>
> Before finalizing and updating production, let me know if anything 
> should be changed.
>
> Reference: link to doc: 
> https://drive.google.com/file/d/0B-5c2BZcSghvcWNvSmhaLWozZWVHdnZZYklxMjAxN3QydDgw/view?usp=sharing
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/TroyManary/EasyPlow/issues/56#issuecomment-139437913>.
>
> Troy Manary <mailto:notifications@github.com>
> September 10, 2015 at 5:41 PM
>
> Robert has reviewed and updated the copy for Operators Home Page.
> He has also proposed some format changes.
>
> The changes are captured in this doc on Google Drive:
> 08 Branding and Marketing_\PR POST\Operators page.docx
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/TroyManary/EasyPlow/issues/56>.
>

-- 
Sent with Postbox <http://www.getpostbox.com>

**Comment by TroyManary** [comment]
Melissa, one last final tweak from Robert.  Text changes only.
I have described it in this ppt:
     Google Drive\EASYPLOW SHARED\04 UI Development\Copy\operator-home-change.pptx

**Comment by melissa-edimensionz** [comment]
Done

**Comment by TroyManary** [comment]
Verified and Closed
