### ISSUE TITLE
Cannot download Insurance Form

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#59]
Going through Operator Registration process, when I get to the 'insurance certificate' page, I click on 'click here to download pre-populated Standardizes Insurance Certificate'.

I get '404: Article Not Found'.

The link it tried to load is:
http://www.easyplow.com/insurance_file/insurance/Certificate_of_Liability_Insurance_EN.pdf

**Comment by rachelle-eplow** [comment]
I haven't run into any issues on any browser. What browser are you using                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Virgin Mobile network.                                                                                                                                                                                                                From: Troy ManarySent: Sunday, September 13, 2015 3:50 PMTo: TroyManary/EasyPlowReply To: TroyManary/EasyPlowSubject: [EasyPlow] Cannot download Insurance Form (#59)Going through Operator Registration process, when I get to the 'insurance certificate' page, I click on 'click here to download pre-populated Standardizes Insurance Certificate'.

I get '404: Article Not Found'.

The link it tried to load is:
http://www.easyplow.com/insurance_file/insurance/Certificate_of_Liability_Insurance_EN.pdf

—Reply to this email directly or view it on GitHub.

**Comment by TroyManary** [comment]
I have the problem in both Chrome and IE.

**Comment by melissa-edimensionz** [comment]
Fixed

**Comment by TroyManary** [comment]
Verified and Closed
