### ISSUE TITLE
Safari-Firefox Login Icon director

### ISSUE THREAD

**Issue by rachelle-eplow** [TroyManary/EasyPlow#6]
Operator Sign Up page states "User" but it should be Operator
<img width="323" alt="operator sign up error" src="https://cloud.githubusercontent.com/assets/13750782/9279829/12aa7116-4288-11e5-9a79-a37e0c17e280.PNG">

**Comment by TroyManary** [comment]
Assigning to Melissa. I think this will be corrected in the coming release of Operator Registration, correct?

**Comment by melissa-edimensionz** [comment]
You betcha - already fixed on development server

**Comment by TroyManary** [comment]
Hi Melissa,
Please re-assign to Rachelle and chnge the labels to 'State: Fixed'.
You could also add a comment that tells her it will be fixed in next 
delivery.
Troy

**Comment by melissa-edimensionz** [comment]
Fixed. Once staging is updated, the fix can be tested.

**Comment by rachelle-eplow** [comment]
Verified as fixed
