### ISSUE TITLE
IE: Operator Registration Page: asterix missing form password fields

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#60]
Strange: the aterixes appear in Chrome but not IE.
In picture below, IE is on left, Chrome on right.

![image](https://cloud.githubusercontent.com/assets/10308999/9838693/8c6eeafc-5a31-11e5-88fd-6025adfb8b2e.png)

**Comment by melissa-edimensionz** [comment]
Fixed

**Comment by TroyManary** [comment]
Verified in both IE and Chrome on staging.
