### ISSUE TITLE
Free Apps label wrong placement

### ISSUE THREAD

**Issue by rachelle-eplow** [TroyManary/EasyPlow#61]
After sign up on the Costumer Login screen.  The email address field is blocked by the "free apps" availability banner.  See screen capture below
![freeapps wrong placement](https://cloud.githubusercontent.com/assets/13750782/9968199/23810c18-5e15-11e5-9e90-0d26067d265f.JPG)

**Comment by melissa-edimensionz** [comment]
Can't recreate, please send browser + version + screen resolution:

http://www.easyplow.com//en/customer-login
http://eplow.staging0.com/en/customer-login

**Comment by rachelle-eplow** [comment]
I cannot recreate either.  The Free Apps banner is gone (non-existent).  This was originally seen on http://eplow.staging0.com/en/customer-login in Google Chrome Version 36
