### ISSUE TITLE
Operator Login Display Profiles Info

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#64]
When I login as an operator, I get the display shown below.
    http://www.easyplow.com/en/operator-login/profile
It should have gone to the dashboard page.
Also, thus display doesn't look right.

![image](https://cloud.githubusercontent.com/assets/10308999/10000939/30b8164c-606d-11e5-8acc-2fc1a15088a3.png)

**Comment by TroyManary** [comment]
I have set this to High Priority since real operators are going to encounter this and probably be turned off.

**Comment by melissa-edimensionz** [comment]
The frontend for Super Administrators hasn't been adjusted, but not something that operators will see. 

This is happening, along with menu issues in the header,  is only because your account is an administrator. Try creating an account that is strictly operator.

**Comment by TroyManary** [comment]
OK.  It works OK for a normal operator account. Closing this as invalid.

**Comment by melissa-edimensionz** [comment]
Please leave open and assigned to me, it should still be fixed.  
Just wanted to let everyone know operators won't see it.

**Comment by TroyManary** [comment]
As requested, re-opened and set priority to Low.

**Comment by melissa-edimensionz** [comment]
Fixed up with a notice to show that your signed in as an administrator (different access rules)

**Comment by TroyManary** [comment]
Verified on Staging and Closed
