### ISSUE TITLE
Schedule Job Field Not Functional

### ISSUE THREAD

**Issue by rachelle-eplow** [TroyManary/EasyPlow#67]
From Customer Login:
1. Input Email Address
2. Input Password
3. Click Schedule Job
Nothing happens once Schedule Job is selected

![schedule job field not functioning](https://cloud.githubusercontent.com/assets/13750782/10009744/4dac9e7a-60af-11e5-9a2f-989bbff58c66.PNG)

**Comment by melissa-edimensionz** [comment]
@AlexEdimensionz

**Comment by melissa-edimensionz** [comment]
hid from views on Staging + production

**Comment by TroyManary** [comment]
Verified on Staging (and easyplow.com) - 'schedule job' is no longer available.
Closed
