### ISSUE TITLE
Operator Sign Up Large Text Tips

### ISSUE THREAD

**Issue by rachelle-eplow** [TroyManary/EasyPlow#7]
Part of the Operator Sign up txt tips show very large

<img width="234" alt="operator sign up large txt tips" src="https://cloud.githubusercontent.com/assets/13750782/9279888/7eae5e7c-4288-11e5-9134-2e559cdbc22e.PNG">

**Comment by melissa-edimensionz** [comment]
Signup up pages are being updated / styled as part of Operator build. Theses are already fixed, just not on staging yet

**Comment by rachelle-eplow** [comment]
Operator Sign up has been verified as fixed.
