### ISSUE TITLE
Prompts in Edit Fields Overflow the Space Available

### ISSUE THREAD

**Issue by rachelle-eplow** [TroyManary/EasyPlow#73]
found on easyplow.com in IE 11 Browser session
1. Clicked on Operator Registration
2. Phone # field indicates form text referring to "custome"

See image
![operator signup wrong field queue phone number](https://cloud.githubusercontent.com/assets/13750782/10063779/61de639c-623f-11e5-95e2-109261e5efc0.PNG)

**Comment by TroyManary** [comment]
The full text is "customer support".

Question for Melissa:
There are a few places where the prompting text does not fit in the field - or when the screen gets squished.   Is there a technique for dealing with this?

**Comment by melissa-edimensionz** [comment]
Any screen less than 1290px starts hiding the in phone number for customer service.  On mobile, the fields scale to 100%, but it would look odd for mobile to jump in at 1290px for this page. 

Suggestions:
- Quick fix: reduce characters for placeholder to 24 or less characters
- or restructure for page so the customer service phone # field has more space.

**Comment by rachelle-eplow** [comment]
tested and verified on staging
