### ISSUE TITLE
Customer Edit Payment Information

### ISSUE THREAD

**Issue by rachelle-eplow** [TroyManary/EasyPlow#74]
![img_0185](https://cloud.githubusercontent.com/assets/13750782/10063977/afc8cff0-6241-11e5-80de-00b4645bdb8f.PNG)
found on easyplow.staging0.com in safari with Ipad Mini
1. Customer Login
2. clicked on "your account" "edit payment information"
On bottom of this page is an "Edit Service Preferences" button which is not operable.  Questioning whether this option should be on that page.

See image

**Comment by TroyManary** [comment]
Melissa,
I have noticed similar buttons on the other Customer Edit displays.  But they are not consistent. I assume the intent is to jump between edit displays.

However, since every page has the 'your account' menu with all the edit options, should we just delete all these buttons?

**Comment by melissa-edimensionz** [comment]
Fixed, was still going through consumer pages. Changes to views are coming over the next week

**Comment by rachelle-eplow** [comment]
cannot verify until next release is available

**Comment by rachelle-eplow** [comment]
tested and verified on staging
