### ISSUE TITLE
Edit Service Area: How to insert points?

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#76]
I am editing the service area and I can easily move and delete points.
If I want to add a point, I can easily insert it next to the flashing point.
But if I want to add somewhere else, how do I do it?
There is noting in the displayed instructions for this.

**Comment by AlexEdimensionz** [comment]
You can't add it anywhere else. There is no other logical way of doing it.
How will we control which one the previous one is?

I can't think of a UI method allowing a user to do that. If we go by 
closest point, they won't be able to make concave shapes.

Alex

e-dimensionz Inc.
Tel: 226.444.8466
Mob: 226.338.8980
http://e-dimensionz.com

**Comment by TroyManary** [comment]
We will have to live with this for now.
Closing as invalid.
