### ISSUE TITLE
French Translation: Home Menu Item

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#78]
Translation from Luci:
    Change: créez un compte client
    To: compte client

**Comment by melissa-edimensionz** [comment]
done

**Comment by TroyManary** [comment]
Verified on Staging and Closed

**Comment by TroyManary** [comment]
Re-opened as I made a mistake in the initial description.
    compte client
should be
   compte clients

**Comment by TroyManary** [comment]
Thanks Melissa for Fixing.
Verified and Closed
