### ISSUE TITLE
Inconsistent Language Operator/Partner

### ISSUE THREAD

**Issue by rachelle-eplow** [TroyManary/EasyPlow#8]
Partner sign up should read operator sign up or visa versa. Consistency required for naming fields.

<img width="218" alt="partner sign up language" src="https://cloud.githubusercontent.com/assets/13750782/9279952/0926ec2c-4289-11e5-9a96-ff20497f2668.PNG">

**Comment by TroyManary** [comment]
Gustave,
We need clarification on terminology on the website.
I suggest the following:
     Customer
     Operator
In some cases, an Operator needs to be further identified as:
     Company
     Driver

**Comment by TroyManary** [comment]
We have settled on Operator instead of Partner.
I believe all the 'partner' terms have been changed to operator.
Closing this Issue.
