### ISSUE TITLE
French Translations: Button and Banners

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#80]
EN: free apps available November 1st!
FR: appli gratuite disponible le 1er novembre!

EN: watch this
FR: regardez la vidéo

EN: partner signup
FR: inscription partenaires

**Comment by TroyManary** [comment]
Melissa,
Gustave has asked to change 'partner signup' to 'operator registration'
So the French will be 'inscription déneigeur'
Please update both English and French.

**Comment by luci-easyplow** [comment]
Hi Troy,

Please note that to date, we have used the plural in French:

inscription déneigeurs

Thanks
Luci

**Comment by melissa-edimensionz** [comment]
The below text wasn;t changed, its an image banner over the module:
EN: free apps available November 1st!
FR: appli gratuite disponible le 1er novembre!

-----------------
The other text changes in this ticket were applied to staging and production.

**Comment by TroyManary** [comment]
Verified on staging that these are done:
   regardez la vidéo
   inscription partenaires

Will open a new issue for Brendan to produce a new logo for 'appli gratuite disponible le 1er novembre!'

Closing this issue.

**Comment by luci-easyplow** [comment]
Hi Troy,

According to Gustave, we are not using "inscription partenaires"/"partner registration".
Only "inscription déneigeurs"/"operator registration"

Thanks

Luci

**Comment by TroyManary** [comment]
Oops! I made a mistake in the comment.
The website is correct: inscription déneigeurs
![image](https://cloud.githubusercontent.com/assets/10308999/10205857/b00c877c-6791-11e5-8fce-88b4e76777b2.png)
