### ISSUE TITLE
http://www.easyplow.com/en/contact

### ISSUE THREAD

**Issue by gustave-eplow** [TroyManary/EasyPlow#81]
when you send a contact us (live site); the confirmation page loads with app logo cut and text in black
![www easyplow com en contact](https://cloud.githubusercontent.com/assets/13750767/10117375/a078a92a-6422-11e5-8994-fa6d50758633.png)

**Comment by melissa-edimensionz** [comment]
Applied an inline fix on production, will update staging template

**Comment by TroyManary** [comment]
Hi Melissa,
I tried this on both easyplow.com and staging.  The text is still black and the logo is still cut off.
Troy

**Comment by melissa-edimensionz** [comment]
Template is not updated on staging yet. 
The thank you message and a formal fix to the button getting cut off will be applied to the template on staging with current page fixes I'm currently doing (re email last night)

Only change on production is the logo isn't cut off by using inline styles. We can't pull template changes to production at this point. 
If the logo is still cut off on production, please send browser + version + screen resolution

Below is the screenshot is what you should see
![eplow](https://cloud.githubusercontent.com/assets/8835635/10202862/e8ee77be-6780-11e5-847c-f542668cc4e3.jpg)

**Comment by TroyManary** [comment]
Sorry.  I didn't understand the impact of the email you sent.
Ill wait til you have updated.

**Comment by TroyManary** [comment]
Verified on Staging Logo is not cutoff and text is blue.
Note: also tested on easyplow.com: Logo is not cutoff but text is still black - that's OK - it will be corrected when we release next.
Closed
