### ISSUE TITLE
Registration email page should remind user to check junk email.

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#82]
Many filters will dump our registration email into a junk folder.
The page we display should remind them to check the junk folder.
I recommend this wording:
     check your email for a confirmation link
     (remember to check your junk or spam folders)

![image](https://cloud.githubusercontent.com/assets/10308999/10144110/cc531f80-65e9-11e5-93d6-a6940adfa88e.png)

**Comment by melissa-edimensionz** [comment]
updated on production (stored in database)

**Comment by TroyManary** [comment]
Verified on both staging and easyplow.com and Closed
