### ISSUE TITLE
Need a french version of the Apps Icon with Nov 1st banner

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#85]
The french pages still use the english banner on the Apps icon.
Need a french version with this translation:
    EN: free apps available November 1st!
    FR: appli gratuite disponible le 1er novembre!

![image](https://cloud.githubusercontent.com/assets/10308999/10202744/578d137a-6780-11e5-8680-edf1ca1c68da.png)

**Comment by TroyManary** [comment]
Brendan e-mailed a new french banner to Melissa.

**Comment by melissa-edimensionz** [comment]
up on staging, also got up on live without pulling new source

**Comment by TroyManary** [comment]
Hi Melissa, I tested on staging and a couple of the french pages still have the english banner:
    http://eplow.staging0.com/fr/enregistrement-des-operateurs
    http://eplow.staging0.com/fr/comment-fonctionne-gopelle
Note: I cleared my history just to make sure.

**Comment by melissa-edimensionz** [comment]
fixed

**Comment by TroyManary** [comment]
Verified on staging.  Got them all now.
Closed
