### ISSUE TITLE
Customer Login is missing from banners

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#86]
On all pages (see below) 'customer login' should be on the banner opposite 'operator login'.
![image](https://cloud.githubusercontent.com/assets/10308999/10202974/80f52fa8-6781-11e5-8bd8-4f8c0f89ba5e.png)
![image](https://cloud.githubusercontent.com/assets/10308999/10202976/85408724-6781-11e5-8b29-5e4ef3e656b7.png)

Note: it is on french pages already.

**Comment by melissa-edimensionz** [comment]
re-enabled

**Comment by TroyManary** [comment]
Verified both home and normal banners.
Closed.
