### ISSUE TITLE
Update to Operator's Home Page

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#87]
As a result of the discussion on good landing pages, Gustave, Robert, and Brendan have produced a new Operator's Home Page (http://eplow.staging0.com/en/operators).

The new page design is:
   Google Drive\EASYPLOW SHARED\04 UI Development\Web Design V1 - Mockups\operator_landingpage_v03.jpg

**Comment by TroyManary** [comment]
The French Translation is here:
   \Google Drive\EASYPLOW SHARED\04 UI Development\Copy\Web_French\Screen Shots_OperatorLanding_FR.pptx

**Comment by melissa-edimensionz** [comment]
@TroyManary  @gustave-eplow @brendan-eplow 
I thought I saw an email regarding the PSD, but can't locate it now. 

Any chance I someone can send the PSD?
If not, just need 1 image, the snowman image below "hey, snowplow operator" (transparent background needed)

**Comment by gustave-eplow** [comment]
Brendan should be able to get that for you.


Gustave Roy
easyplow.com
gustave@easyplow.com

**Comment by luci-easyplow** [comment]
Troy,

You need revised translation for this updated Operator's English copy. I'll try to get that to you before end of day Friday.

Thanks
Luci

**Comment by luci-easyplow** [comment]
Here is the translation for the updated Operator Home page
[updated operator landingpage_v0X BIL.docx](https://github.com/TroyManary/EasyPlow/files/6968/updated.operator.landingpage_v0X.BIL.docx)

**Comment by melissa-edimensionz** [comment]
@TroyManary, @gustave-eplow 
The translation (updated operator landingpage_v0X BIL.docx) seems to be for the current operators page, not the new operators page being created.   Are we doing both?

I'll use this
\Google Drive\EASYPLOW SHARED\04 UI Development\Copy\Web_French\Screen Shots_OperatorLanding_FR.pptx

 for the new operators page and hold off on updating the current live operators page

**Comment by melissa-edimensionz** [comment]
@TroyManary @gustave-eplow 

The operators new page is a jpg, I iust cropped out the image for 
"sign up before OCTOBER 31 for the chance to win an iPad mini WITH DASHBOARD MOUNT"

(can't extract image layers from a jpg)

Can change to text, but I will need the single elements for the images in this section that aren't text
Or, can keep the contest block as an image, will just need the translated jpg

![ipad-mini](https://cloud.githubusercontent.com/assets/8835635/10257310/8eb9b06a-6924-11e5-821c-4e683325f714.jpg)

**Comment by melissa-edimensionz** [comment]
@gustave-eplow @TroyManary 

New operators page set up on staging for review:
http://eplow.staging0.com/_operator-landing/
http://eplow.staging0.com/_operator-landing/index-fr.html

Let me know if anything needs to be changed

**Comment by TroyManary** [comment]
One small typo to fix (s on the end of allow):
Change:
  easyplow allow homeowners to order snow removal, one job at a time.
To:
  easyplow allows homeowners to order snow removal, one job at a time.

**Comment by melissa-edimensionz** [comment]
fixed below:

One small typo to fix (s on the end of allow):
Change:
easyplow allow homeowners to order snow removal, one job at a time.
To:
easyplow allows homeowners to order snow removal, one job at a time.

**Comment by TroyManary** [comment]
Verified on EasyPlow.com and gopelle.com.
Closed.
