### ISSUE TITLE
Twitter: French Twitter Account Needed

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#89]
Is there a French Twitter Account?
Unfortunately, http://twitter.com/gopelle is taken by a Republican (GOP) named Elle --> gopelle

Gustave, please setup a twitter account and ensure that it gets updated to match the english account.

**Comment by TroyManary** [comment]
Let's try go.pelle which matches facebook.
Or go_pelle.

**Comment by brendan-eplow** [comment]
We already have @go_pelle on Twitter

**Comment by TroyManary** [comment]
Excellent!
Closing the Issue as Invalid.
