### ISSUE TITLE
Contact Info: Add Support Phone Number

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#91]
Add this to the Contact page below 'Web'
     Support: 1-877-403-8082

Note: If you browser shows the above phone number with a Skype symbol and 'Free'  that is not intended for the web page.  It happens automatically in your browser with the Skype plugin - to get rid of it, click on the Skype icon in top right of browser and turn off number highlighting.

![image](https://cloud.githubusercontent.com/assets/10308999/10286533/24a64898-6b5c-11e5-9dd6-73d894e09421.png)

**Comment by melissa-edimensionz** [comment]
Added support #, but space restrictions with app button and can;t apply layout adjustments on production (it requires absolute positioning)

On production, removed line between address & email to "fit"
On staging, left line betwwen address & email so it can be fixed once we can move changes to production

**Comment by TroyManary** [comment]
Verified on English and French.
Closed
