### ISSUE TITLE
Operator Registration Workflow Simplification

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#93]
Gustave has been through the Registration workflow with a couple of Operators and the current workflow is difficult since they get to Insurance and get stuck.  We want to get them 'registered' ASAP.

There is also concern that requiring payment info before we have approved them is not acceptable.

So, we have simplified the registration workflow by deferring Insurance and Payment Info until after Registration.

![image](https://cloud.githubusercontent.com/assets/10308999/10312522/a00495b8-6c19-11e5-9aab-b11593e0518a.png)

**Comment by TroyManary** [comment]
As a result of this change, we need to ensure the operator knows there is more info required (see 2 orange boxes in diagram).

I will submit 2 new issues to cover these additional changes.

**Comment by TroyManary** [comment]
Alex,
Is it possible to make this change on the live site ASAP?  Gustave would like it to be done before they send push e-mails to operators (later today is possible).

**Comment by AlexEdimensionz** [comment]
Done this. I will push code live tomorrow and do DB migrations

**Comment by TroyManary** [comment]
Verified on Staging and Closed.
