### ISSUE TITLE
Operator Registration Workflow: Inform Operator of Incomplete Info

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#95]
As a result of Issue #93, operators will be registered without providing their insurance certificate or payment info.

So, each time they login and they arrive at the Operator dashboard, it must inform them of this missing info.

Add a status note to the dashboard:

If insurance has not be submitted:
Your account has not been activated.  Please submit an Insurance Certificate.

If insurance is submitted, but not approved:
Your account has not been activated.  We are reviewing your Insurance Certificate and will inform you when it has been approved (within 5 days of submission).

If account is activated, but no payment info:
Your account is activated but we do not have your payment information.  Please update your payment info.

**Comment by TroyManary** [comment]
En Francais (Luci):
If insurance has not be submitted:
Votre compte n’a pas été activé. Veuillez soumettre votre certificat d’assurance.

If insurance is submitted, but not approved:
Votre compte n’a pas été activé. Nous examinons votre certificat d’assurance et vous ferons savoir quand il aura été approuvé (dans les cinq jours suivant la demande).

If account is activated, but no payment info: 
Votre compte a été activé, mais nous n’avons pas reçu vos informations de paiement. Veuillez mettre à jour ces données.

**Comment by TroyManary** [comment]
We also need a couple of hyperlinks.
If insurance has not been submitted, the text 'Insurance Certificate' should link to the existing Insurance Page (which allows download and submission).

If payment info has not been provided, the text 'payment info' should link to the existing Edit Payement Info Page.

**Comment by TroyManary** [comment]
Alex, Note that this is not needed until the Operator Registration workflow is updated as described in Issue #93.

**Comment by TroyManary** [comment]
As discussed on telecon yesterday, this must be done for 1-Nov at same time as issues #93

**Comment by AlexEdimensionz** [comment]
Done they are all in the overrides in Joomla Admin

**Comment by TroyManary** [comment]
Verified on Staging and Closed.
