### ISSUE TITLE
Typo in "About Us" page - misspelling of company's name

### ISSUE THREAD

**Issue by paty-eplow** [TroyManary/EasyPlow#96]
There is a typo on the first sentence of the page. It says "plow corp. (easyplow)..." it should say "Easyplow corp. (easyplow)..." see attached image.

![e-plow1](https://cloud.githubusercontent.com/assets/14628456/10313776/53ee1536-6c1f-11e5-9e03-5719dda95791.JPG)

**Comment by gustave-eplow** [comment]
should say:
EN : EPLOW CORP. (easyplow.com)
FR : EPELLE CORP. (gopelle.com)

paty-eplow wrote:

**Comment by melissa-edimensionz** [comment]
fixed

**Comment by paty-eplow** [comment]
Verified on staging.
