### ISSUE TITLE
Operator Registration - 'Are you Authorized' should be Mandatory

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#97]
Gustave says that only people who are authorized to represent the company should be allowed to register.

On the Operator Registration Info form, make the checkbox mandatory.  It should have an orange star and the box must be checked before they can proceed,

**Comment by melissa-edimensionz** [comment]
@TroyManary 
Change may need to hold until we can commit source changes to live. Sending to Alex in case he can find a work around

**Comment by gustave-eplow** [comment]
that's ok

Gustave Roy
easyplow.com
gustave@easyplow.com

**Comment by AlexEdimensionz** [comment]
Done and On staging

**Comment by TroyManary** [comment]
Verified on Staging in English and French.
Closed
