### ISSUE TITLE
Operators don't need to specify 'Position' and 'Years in Business'

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#99]
Gustave says this is an annoyance for operators to fill in and we really don't care.
Remove these fields from the registration and account pages.

This is a very low priority change.  Only do it when you are updating the page for other reasons.

**Comment by melissa-edimensionz** [comment]
@TroyManary 
Change may need to hold until we can commit source changes to live. Sending to Alex in case he can find a work around

**Comment by melissa-edimensionz** [comment]
wrong ticket, deleted comment

**Comment by melissa-edimensionz** [comment]
Hid fields. Can't adjust views until we can commit source changes

**Comment by TroyManary** [comment]
Verified on Staging in English & French.
Note: French error message needs to be translated to french - will submit a new issue for that
Closed.
